replicaCount: 1

image:
  repository: 149536467399.dkr.ecr.us-east-1.amazonaws.com/group1/frontend
  tag: latest

config:
  baseUri: ""
  port: 3001

resources:
  limits:
    memory: "400Mi"
    cpu: 0.5
  requests:
    memory: "300Mi"
    cpu: 0.25

probes:
  liveness:
    initialDelaySeconds: 30
    periodSeconds: 10
  readiness:
    initialDelaySeconds: 10
    periodSeconds: 5

hpa:
  minReplicas: 1
  maxReplicas: 3
  metrics:
    cpu: 60
    memory: 40

