apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-backend-config
  labels:
    app: {{ .Release.Name }}-backend
data:
  SERVER_NAME: server
  SERVER_HOST: "http://localhost"
  MONGODB_USER: "adminuser"
  MONGODB_PASS: "password123"
  MONGODB_HOST: "mongo-svc"
  MONGODB_PORT: "27017"

