apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
  labels:
    app: {{ .Release.Name }}-backend
spec:
  type: LoadBalancer
  selector:
    app: {{ .Release.Name }}-backend
  ports:
  - port: 80
    name: http
    targetPort: 3000

