apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-mongo-data-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: {{ .Values.storage.capacity }}
  hostPath:
    path: {{ .Values.storage.hostPath }}

