apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mongo-creds
type: Opaque
data:
  username: {{ .Values.credentials.username | b64enc }}
  password: {{ .Values.credentials.password | b64enc }}

