apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongo-svc
  labels:
    app: {{ .Release.Name }}-mongo
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: {{ .Release.Name }}-mongo
  type: ClusterIP

