replicaCount: 1

image:
  repository: 149536467399.dkr.ecr.us-east-1.amazonaws.com/group1/backend
  tag: latest

resources:
  limits:
    memory: "200Mi"
    cpu: 0.25
  requests:
    memory: "100Mi"
    cpu: 0.18

hpa:
  minReplicas: 1
  maxReplicas: 3
  metrics:
    cpu: 60
    memory: 40

